### ISSUE TITLE
[FEATURE] Domain control from path object

### ISSUE THREAD

**Issue by Acrontum-Carmichael** [acrontum/generate-it#17]
**Is your feature request related to a problem? Please describe.**
Would like tighter control of the domain naming and not only use the 1st segment of the path.

**Describe the solution you'd like**
```
x-domainName: UserManagement
```

**Comment by jonmanga** [comment]
This will be good for migrating older projects.

**Comment by Acrontum-Carmichael** [comment]
https://acrontum.github.io/generate-it/#/_pages/features?id=nested-stub-files-aka-nested-domains

This is now solved in another way by controlling from the package rc/cli args not the openapi spec
