### ISSUE TITLE
[FEATURE] granular lookahead control at path level

### ISSUE THREAD

**Issue by acrontum-revah** [acrontum/generate-it#2]
Controlling the segments lookahead via the CLI is great,
But would be even nicer overriding it via the OpenAPI definition file for specific paths.

e.g. x-nodegen-lookahead

**Comment by Acrontum-Carmichael** [comment]
Currently this feature was removed.. needs addressing

**Comment by Acrontum-Carmichael** [comment]
This is now resolved with  https://acrontum.github.io/generate-it/#/_pages/features?id=nested-stub-files-aka-nested-domains
