### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by p-mcgowan** [acrontum/generate-it#26]
**Describe the bug**
tsc complains about uuid/v4 types and implicit any's in process.ts

**To Reproduce**
npm i generate-it@5.6.5
npm run generate:nodegen

**Expected behavior**
no compilation errors 

**Node & NPM version**
node: v13.13.0
npm: 6.14.5

**Operating system:**
 - OS: ubuntu
 - Version 18.04.4

**Additional context**
```
src/http/nodegen/request-worker/process.ts(4,20): error TS7016: Could not find a declaration file for module 'uuid/v4'. '/home/patrickmcgowan/source/acrontum/bmw/dsd/user-management/user-management/node_modules/uuid/v4.js' implicitly has an 'any' type.
  Try `npm install @types/uuid` if it exists or add a new declaration (.d.ts) file containing `declare module 'uuid/v4';`
src/http/nodegen/request-worker/process.ts(40,32): error TS7031: Binding element 'callId' implicitly has an 'any' type.
src/http/nodegen/request-worker/process.ts(40,40): error TS7031: Binding element 'error' implicitly has an 'any' type.
src/http/nodegen/request-worker/process.ts(40,47): error TS7031: Binding element 'response' implicitly has an 'any' type.
```

temp fix:
`npm i @types/uuid`
replace 
```diff
-      const handleMessage = ({ callId, error, response }) => {
+      const handleMessage = ({ callId, error, response }: any) => {
```
/src/http/nodegen/request-worker/process.ts

**Comment by Acrontum-Carmichael** [comment]
@p-mcgowan this looks to be for the server tpl not the core.

The fix you wrote looks correct, would be easiest if you could just send the fix straight to dev branch on the tpl repo then merge it to master.

**Comment by p-mcgowan** [comment]
yep - realized that after the fact

thanks
