### ISSUE TITLE
[BUG] Unclear wording on package json diff

### ISSUE THREAD

**Issue by Acrontum-Carmichael** [acrontum/generate-it#30]
**Describe the bug**
ReGenerate an existing server after new changes to the package.json.njk in a remote tpl repo. The output diff doesn't clearly state what it means. It indicates the packages have actually been updated where as it should read the user should update them.

It should read:
"Some packages in the master template have been updated, please compare the table below and manually update your API"

![MicrosoftTeams-image](https://user-images.githubusercontent.com/16192806/82350241-60e9d680-99fb-11ea-83b6-b77252082fd9.png)

**Comment by p-mcgowan** [comment]
closed in 7812e23771bca2b84616ccd3aa5d12eb1f5a983a?

**Comment by p-mcgowan** [comment]
Also it may have been just me, but at first the wording "Changed to" and "from" caused a fair bit of confusion at first. Maybe "Upsteam/Master" and "Local" would be more clear?

**Comment by Acrontum-Carmichael** [comment]
Yup.. the whole naming there is quite confusing, let just leave this issue open till that one is also resolved.
