### ISSUE TITLE
[BUG] `req` parameter in Domain interface has type any

### ISSUE THREAD

**Issue by jonmanga** [acrontum/generate-it#31]
**Describe the bug**
`req` parameter has type `any` in methods of the Domain interfaces that take the request object.

This is a sample extract of a method in a Domain interface

`authLogin(body: AuthPasswordResetPostBody, req: any): Promise<any>;`

**To Reproduce**
1. Write a post definition that includes `x-passRequest`

For example:
`src/auth/login/post/`

```yaml
tags:
  - auth
summary: "Authenticates a user against provided credentials"
description: ""
operationId: authLogin
parameters:
  - in: body
    name: authLoginPostBody
    description: The users email
    schema:
      $ref: ../../../definitions/auth/login/post.yml
produces:
  - "application/json"
responses:
  "200":
    description: successful operation
    schema:
      $ref: ../../../definitions/auth/TokenUser.yml
  "401":
    description: Unauthenticated request
  "422":
    description: Unprocessable Entity
x-passRequest: true
```
2. Generate api
3. Open the `AuthDomainInterface`

**Expected behavior**
The `authLogin` method in the `AuthDomainInterface` should have the type `NodegenRequest` or `Request` from express.

**Comment by Acrontum-Carmichael** [comment]
This one is actually a little more involved, the return type should either be as you stated... or... for no schema the response should be void. This latter bit is not done yet and so to get the interface live it was left as any.

I think as the impact here is quite low we can tackle it a little later :)

**Comment by Celleb** [comment]
Is this bug not closed yet?

**Comment by p-mcgowan** [comment]
Seems like the latest builds are setting the type to `NodegenRequest`, so it appears to have been fixed at some point.
