### ISSUE TITLE
[BUG] out of memory when diff'ing

### ISSUE THREAD

**Issue by p-mcgowan** [acrontum/generate-it#42]
**Describe the bug**

![image](https://user-images.githubusercontent.com/8646562/86931812-dab75a00-c138-11ea-9445-ec71a2c02cab.png)

**To Reproduce**
Happens occasionally with `npm run generate:nodegen`
```
  "generate:nodegen": "generate-it ../user-management-swagger/build/api_1.0.0.yml -m -t https://github.com/acrontum/openapi-nodegen-typescript-server.git",
```

**Expected behavior**
Not out of memory

**Node & NPM version**
node: v13.13.0
npm: 6.14.5

**Operating system:**
 - OS: Ubuntu
 - Version 18.04.4 LTS

**Additional context**
Can't reproduce, running it again without making changes seems to work fine the second time

**Comment by Acrontum-Carmichael** [comment]
There is the option to run generate without calling the diff tool.

I have noticed on occasion this happening too but also cannot replicate it on demand.

**Comment by p-mcgowan** [comment]
Yeah, it seems like it's just one of those things.

It's not a big issue, since running again fixes it, but maybe it will fix itself in time. Seems to have started within the last 5 or 6 releases (maybe?) but to my knowledge, the diff stuff has not changed much

**Comment by Acrontum-Carmichael** [comment]
I have not seem this one happen in a very long time - coupled with the node_module dir parsing resolution.. i think this one is now solved.. for now :D

**Comment by p-mcgowan** [comment]
yeah, and it's just not significant to track down, was debating closing it too. 
i saw it relatively recently but actually might have been the .git and node_modules as you mentioned.
