### ISSUE TITLE
[FEATURE] support null in templates

### ISSUE THREAD

**Issue by p-mcgowan** [acrontum/generate-it#58]
**Is your feature request related to a problem? Please describe.**
If i want to allow a string param to be validated with min length, but also allow `null` (to unset), I can't do that with the joi params

**Describe the solution you'd like**
with `user/model.yml` as:
```yaml
type: object
properties:
  id:
    type: number
  username:
    required: true
    type: string
  email:
    minLength: 1
   pattern: maybe
    type: ['string', 'null']
```

then the generated joi validation should be something like this
```typescript
usersUserIdPatch: {
    body: Joi.object({
      id: Joi.number(),
      username: Joi.string().allow(''),
      email: Joi.string().min(1).allow(null),
    }
  },
```

**Describe alternatives you've considered**
removing the min length param and validating in the domain - manually converting defined, empty string to `null`

**Additional context**
We could either do this in the swagger as above, or have a nullable flag somwhere (this may not be supported / standard)

The `pathParamsToJoi` function doesn't currently support array types as above - would have to update it to do some more checking
```typescript
  public pathParamsToJoi (param: any, options: PathParamsToJoi): string {
    if (!param) {
      console.log(param, options);
      return;
    }
    const {paramTypeKey} = options;
    let validationText = param.name ? `'${param.name}'` + ':' : '';
    const isRequired = (options.requiredFields && options.requiredFields.includes(param.name)) || param.required;
    const type = param.type || param.schema.type;
    // for the email spec above: { name: 'email', minLength: 1, type: [ 'string', 'null' ] }
    // so this just results in "any" typings
    if (['string', 'number', 'integer', 'boolean'].includes(type)) {
```

**Comment by Acrontum-Carmichael** [comment]
this should only be added with the spec file does not state the attr is required

**Comment by p-mcgowan** [comment]
that would be cool - defaulting to allow null unless `required: true`
