### ISSUE TITLE
[BUG] domain segment not producing proper routes

### ISSUE THREAD

**Issue by Celleb** [acrontum/generate-it#59]
**Describe the bug**
The generator is not producing expected routes when used with segments.
The routes are camel-cased and the parameters are dropped.
Example of wrong routes:
```typescript
export default function (app: express.Application, basePath = '') {
  
  app.use(basePath + '/auth', authRoutes())
    
  app.use(basePath + '/hr', hrRoutes())
    
  app.use(basePath + '/hrEmployees', hrEmployeesRoutes())
    
  app.use(basePath + '/hrRoles', hrRolesRoutes())
    
  app.use(basePath + '/hrUser-roles', hrUserRolesRoutes())
    
  app.use(basePath + '/hrUsers', hrUsersRoutes())
    
  app.use(basePath + '/permissions', permissionsRoutes())
 }
```

**To Reproduce**
1. Use swagger definitions with nested routes
2. set `segmentFirstGrouping" 2` in `.boatsrc`
3. Generate to the backend

Directory structure:
<img width="315" alt="Screenshot 2020-09-02 at 09 41 27" src="https://user-images.githubusercontent.com/700835/91960596-5fbe8a00-ed0a-11ea-90c1-fff5ea26fd23.png">

**Expected behavior**
Something like this:

```typescript
export default function (app: express.Application, basePath = '') {
  
  app.use(basePath + '/auth', authRoutes())
    
  app.use(basePath + '/hr', hrRoutes())
    
  app.use(basePath + '/hr/:id/employee', hrEmployeesRoutes())
    
  app.use(basePath + '/hr/:id/roles', hrRolesRoutes())
    
  app.use(basePath + '/hr/:id/user-roles', hrUserRolesRoutes())
    
  app.use(basePath + '/hr/:id/users', hrUsersRoutes())
    
  app.use(basePath + '/permissions', permissionsRoutes())
 }
```

**Node & NPM version**

**Operating system:**
 - OS: [e.g. LinuxMint]
 - Version [e.g. 19.2]

**Additional context**

**Comment by Acrontum-Carmichael** [comment]
Which version are you working with?

**Comment by Celleb** [comment]
5.19.1

**Comment by Acrontum-Carmichael** [comment]
please update this is fixed on the later version.

if it is all good could you close the issue

**Comment by Celleb** [comment]
I can't see where the segment routes are imported from.

**Comment by Acrontum-Carmichael** [comment]
There was a bug fix and new data available from the core.

https://github.com/acrontum/openapi-nodegen-typescript-server/blob/master/src/http/nodegen/routesImporter.ts.njk

If you are using a custom template you will need to update it.
