### ISSUE TITLE
[BUG] Async API RabbitMQ | paramsOutputReducer does not return the correct schema structure

### ISSUE THREAD

**Issue by acrontum-revah** [acrontum/generate-it#64]
**Describe the bug**
The generated publish functions inside the `RabbitMQService.ts` file, are publishing messages with empty payloads since the `objectReduceByMap` call is not receiving (second argument) the correct schema structure that was defined in the async API file.
After looking into the source code of generate-it, I suspect reason being is that the provided async API file does not contain any http status.

**To Reproduce**
- Template in use: https://github.com/acrontum/generate-it-asyncapi-rabbitmq.git
- Please try to generate using the following async api:
```yaml
asyncapi: 2.0.0
info:
  title: rabbitmq_d
  version: 0.0.1
  description: rabbitmq asyncapi
  license:
    name: Apache 2.0
    url: 'https://www.apache.org/licenses/LICENSE-2.0'
defaultContentType: application/json
channels:
  /core/user-create:
    description: User has been created
    publish:
      operationId: coreUserCreatePublish
      message:
        contentType: application/json
        payload:
          $ref: '#/components/schemas/CoreUserCreate'
  /core/user-update:
    description: User has been created
    publish:
      operationId: coreUserUpdate
      message:
        contentType: application/json
        payload:
          $ref: '#/components/schemas/CoreUserUpdate'
components:
  schemas:
    CommonUserBaseModel:
      type: object
      properties:
        salutation:
          type: string
        firstName:
          type: string
        lastName:
          type: string
        email:
          type: string
        active:
          type: boolean
        deletedAt:
          type: string
        createdAt:
          type: string
        updatedAt:
          type: string
    CommonUserModel:
      allOf:
        - type: object
          properties:
            id:
              type: number
        - $ref: '#/components/schemas/CommonUserBaseModel'
    CoreUserCreate:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/CommonUserModel'
    CoreUserUpdate:
      type: object
      properties:
        userId:
          type: number
        user:
          $ref: '#/components/schemas/CommonUserBaseModel'
```
- see `publishCoreUserCreatePublish` function inside `RabbitMQService.ts`

**Expected behavior**
Generate-it should also accommodate async api files that do not contain http status numbers.
objectReduceByMap to receive in the second argument the correct schema structure that was defined in the async api file.

**Node & NPM version**
Node: 12.14.1
NPM: 6.14.8

**Operating system:**
 - OS: Windows 10 (WSL 2)
 - Version [e.g. 19.2]

**Comment by Acrontum-Carmichael** [comment]
The test used to catch these changes but the updates no do not.

Previous hash check on the generated output:
```
  it('should return the correct hash for the domain folder', async () => {
    const options = {
      files: {include: ['*.ts']}
    };
    const hash = await hashElement(testServerPath, options);
    expect(hash.hash).toBe('+l0qbqc4Jbkw1LyBlZk3MKcHUK0=');
  });
```

Essentially async doesn't have status codes which is why an empty object is now returned from:  https://github.com/acrontum/generate-it/blob/master/src/lib/template/helpers/paramsOutputReducer.ts

**Comment by Acrontum-Carmichael** [comment]
@p-mcgowan  i will take a look at this now is also causing issues at my end too
