### ISSUE TITLE
[FEATURE] 

### ISSUE THREAD

**Issue by atillabaspinar** [acrontum/generate-it#69]
Problem:
Objects having null properties are not allowed by Joi

Description:
Consider we make a request with an object
```
user = {
 name: 'john',
 age: null
}
```
This does not pass Joi check since age is null. 
This becomes a problem with some Angular features like form.reset() which resets values to null. 
because the code generates `Joi.string().allow('')`
i think it should include null like `Joi.string().allow('').allow(null)`

related code is at SwaggerUtils.ts:
```
      if (type === 'string' && !isRequired && !param.minLength) {
        validationText += `.allow('')`;
      }
```

**Comment by p-mcgowan** [comment]
closing as duplicate https://github.com/acrontum/generate-it/issues/58

**Comment by p-mcgowan** [comment]
I believe this may also require changes in the templates, but not 100%
